Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.box_url = "https://app.vagrantup.com/centos/boxes/7"

	config.vm.provision "shell", privileged: false, inline: <<-SHELL
		sudo yum install -y net-tools
	SHELL

	config.vm.hostname = "lmatarisS"
	config.vm.provider "virtualbox" do |v|
		v.name = "lmatarisS"
		v.memory = 2048
		v.cpus = 1
	end

	config.vm.network "private_network", ip: "192.168.56.110"
	config.vm.provision "shell", privileged: false, inline: <<-SHELL
		export K3S_KUBECONFIG_MODE="644"

		curl -sfL https://get.k3s.io | sh -

		echo "alias k='kubectl'" >> /home/vagrant/.bashrc

		kubectl apply -f /vagrant/confs/app-one.yaml
		kubectl apply -f /vagrant/confs/app-two.yaml
		kubectl apply -f /vagrant/confs/app-three.yaml
		kubectl apply -f /vagrant/confs/ingress.yaml
	SHELL
end
