version: "3.9"
services:
#==== FRONT ===================================================================#
  front:
    container_name: front
    build: containers/front
    image: front
    env_file: .env
    depends_on:
     - database
     - back
    ports:
      - 80:80
    volumes:
      - ./apps/front/:/var/www/html/
    networks:
      - transcendence
    stdin_open: true
    restart: unless-stopped

#==== BACK ====================================================================#
  back:
    container_name: back
    build: containers/back
    image: back
    env_file: .env
    depends_on:
      - database
    ports:
      - 3030:3030
    volumes:
      - ./apps/back:/var/www/html/back
    networks:
      - transcendence
    stdin_open: true
    restart: unless-stopped
#==== POSTGRESQL ==============================================================#
  database:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcendence
    networks:
      - transcendence
    restart: unless-stopped

#============================================================================#
networks:
  transcendence:
    name: transcendence
    driver: bridge
